In [1]:
import tensorflow_datasets as tfds

import tensorflow as tf
from tensorflow.keras.layers import Dense, Flatten, Conv2D
from tensorflow.keras import Model
import PIL
import tensorflow as tf

from tensorflow.keras import datasets, layers, models
import matplotlib.pyplot as plt

In [2]:
img_train = tfds.as_numpy(tfds.load(
    'colorectal_histology',
    split=['train'],
    batch_size=-1,
    
))

Instructions for updating:
Use `tf.data.Dataset.get_single_element()`.


Instructions for updating:
Use `tf.data.Dataset.get_single_element()`.


In [3]:
lab=img_train[0]['label']
img=img_train[0]['image']

In [4]:
print(img.shape)

(5000, 150, 150, 3)


In [5]:
model = models.Sequential()
model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(150, 150, 3)))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))

In [6]:
model.add(layers.Flatten())
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(8))

In [7]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 148, 148, 32)      896       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 74, 74, 32)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 72, 72, 64)        18496     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 36, 36, 64)       0         
 2D)                                                             
                                                                 
 conv2d_2 (Conv2D)           (None, 34, 34, 64)        36928     
                                                                 
 flatten (Flatten)           (None, 73984)             0

In [8]:
img=img/255

In [9]:
model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

In [10]:
history = model.fit(img, lab, epochs=30, 
                    validation_data=(img, lab))

Epoch 1/30
157/157 [==============================] - 18s 53ms/step - loss: 1.0697 - accuracy: 0.5480 - val_loss: 0.9477 - val_accuracy: 0.6714
Epoch 2/30
157/157 [==============================] - 6s 35ms/step - loss: 0.7544 - accuracy: 0.6838 - val_loss: 0.6695 - val_accuracy: 0.6752
Epoch 3/30
157/157 [==============================] - 6s 36ms/step - loss: 0.6349 - accuracy: 0.7318 - val_loss: 0.4759 - val_accuracy: 0.8270
Epoch 4/30
157/157 [==============================] - 6s 36ms/step - loss: 0.5460 - accuracy: 0.7828 - val_loss: 0.4151 - val_accuracy: 0.8322
Epoch 5/30
157/157 [==============================] - 6s 36ms/step - loss: 0.4508 - accuracy: 0.8122 - val_loss: 0.3899 - val_accuracy: 0.7804
Epoch 6/30
157/157 [==============================] - 6s 35ms/step - loss: 0.4321 - accuracy: 0.8258 - val_loss: 0.4102 - val_accuracy: 0.7856
Epoch 7/30
157/157 [==============================] - 6s 35ms/step - loss: 0.4117 - accuracy: 0.8464 - val_loss: 0.2571 - val_accuracy: 0.919

In [11]:
a=model.predict(img)

In [12]:

def mayor(vec):
  for i,j in enumerate(vec):
    if j==max(vec):
      return i
      

In [13]:
import numpy as np
l=np.array([mayor(a[i]) for i in range(5000)])

In [14]:
print(l)

[4 5 5 ... 5 4 4]


In [15]:
print(lab)

[4 5 5 ... 5 4 4]


In [16]:
from sklearn.metrics import confusion_matrix

In [17]:
confusion_matrix(lab, l)

array([[624,   0,   0,   0,   0,   1,   0,   0],
       [  0, 625,   0,   0,   0,   0,   0,   0],
       [  3,   0, 610,   1,   2,   9,   0,   0],
       [  0,   0,   0, 625,   0,   0,   0,   0],
       [  0,   0,   0,   0, 624,   0,   1,   0],
       [  0,   0,   0,   0,   0, 625,   0,   0],
       [  0,   0,   0,   0,   0,   0, 611,  14],
       [  0,   0,   0,   0,   0,   0,  11, 614]])